version: "{build}"

# Do a shallow clone of the repo to speed up build
clone_depth: 1

# Install needed build dependencies
before_build:
  # Download and install the required version of Mono
  - ps: Start-FileDownload "http://download.mono-project.com/archive/4.2.1/windows-installer/mono-4.2.1.102-gtksharp-2.12.30-win32-0.msi" -FileName "mono.msi"
  - ps: Start-FileDownload "https://github.com/activescott/lessmsi/releases/download/v1.4/lessmsi-v1.4.zip" -FileName "lessmsi.zip"
  - 7z e lessmsi.zip > NUL
  - lessmsi x mono.msi
  # Set environmental variables and add to PATH
  - SET MONO_WIN=%APPVEYOR_BUILD_FOLDER%\mono\SourceDir\Mono
  - for /f "delims=" %%a in ('%%CYG_PATH%% %%MONO_WIN%%') do @set MONO=%%a
  - SET PKG_CONFIG_PATH=%MONO%/lib/pkgconfig
  - SET MACHINECONFIG=%MONO_WIN%\etc\mono\4.5\machine.config
  - SET PATH=%PATH%;%MONO%\bin
  - SET SOURCE_FILES="Resources\basic.exe %MONO_WIN%\mscorlib.dll %MONO_WIN%\System.dll %MONO_WIN%\System.Core.dll %MONO_WIN%\System.Xml.dll"

build_script:
  # Create temp files from source file and dependencies
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; mkbundle \"$SOURCE_FILES\" -c -o temp.c -oo temp.o --machine-config \"$MACHINECONFIG\""'
  - ps: (Get-Content temp.c -Raw) | Foreach-Object {$_ -replace "int main(.|\n)*", (Get-Content Resources\win.c -Raw)} | Set-Content temp.c
  - ps: (Get-Content Resources\resource.rc -Raw) | Foreach-Object {$_ -replace "(?<version>\d[,|\.]\d[,|\.]\d[,|\.])\d", "`${version}$env:APPVEYOR_BUILD_NUMBER" } | Set-Content Resources\resource.rc
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; windres -i Resources/resource.rc -o resource.o"'
  # Create final file from temp files
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; export MONO_PATH=$MONO; export PKG_CONFIG_PATH=$PKG_CONFIG_PATH; i686-pc-mingw32-gcc -g -o CSharpCompiler.exe -Wall temp.c `pkg-config --cflags --libs mono-2 | sed \"s/-mwindows//g\"` temp.o resource.o"'

on_success:
  # Download and unpack UPX for compression
  - ps: Start-FileDownload "http://upx.sourceforge.net/download/upx391w.zip" -FileName "upxw.zip"
  - 7z e upxw.zip -aoa > NUL
  # Compress using UPX and compression level 9
  - upx.exe -q -9 CSharpCompiler.exe %MONO_WIN%/bin/mono-2.0.dll
  # If from master branch and not a pull request, deploy to Oxide repo on GitHub
  - ps: >-
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null) {
        echo "Skipping deployment for pull request!"
      } elseif ($env:APPVEYOR_REPO_BRANCH -ne 'master') {
        echo "Skipping deployment for non-master branch!"
      } else {
        git config --global user.email "appveyor@appveyor.com"
        git config --global user.name "AppVeyor"
        git clone -q https://$env:GITHUB_TOKEN@github.com/OxideMod/Oxide.git Oxide
        cp -force CSharpCompiler.exe Oxide\Extensions\Oxide.Ext.CSharp\Dependencies
        cp -force $env:MONO_WIN\bin\mono-2.0.dll Oxide\Extensions\Oxide.Ext.CSharp\Dependencies
        cd Oxide
        git add .
        git commit -m ("CSharpCompiler Windows build $env:APPVEYOR_BUILD_NUMBER from https://github.com/$env:APPVEYOR_REPO_NAME/commit/" + $env:APPVEYOR_REPO_COMMIT.Substring(0,7))
        git push -q origin master
      }

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
  - provider: Slack
    auth_token:
      secure: ovO33N9fONSaYavRURafM85w6dEgOdNFwtzc4rASuUNh4MNn96ktsevPcCpQQLN/
    channel: updates

environment:
  global:
    CYG_BASH: C:\cygwin\bin\bash
    CYG_PATH: C:\cygwin\bin\cygpath
    GITHUB_TOKEN:
      secure: p9D5rPOLMYjKiUU1N8pObsKXhqlM8k4WWjTnEauLiGdJQLGPOwIml4JiQXkACQpe

test: off
deploy: off
