sudo: false
language: csharp
mono: beta

addons:
  apt:
    packages:
    - upx-ucl

script:
  # Create temp files from source file and dependencies
  - mkbundle Resources/basic.exe -c -o temp.c -oo temp.o --deps
  # Create final file from temp files
  - gcc -g -o CSharpCompiler -Wall temp.c `pkg-config --cflags --libs mono-2` temp.o

after_success:
  # Copy libmono shared library to project directory
  - cp /usr/lib/libmonoboehm-2.0.so.1.0.0 libmonoboehm-2.0.so.1 && chmod +x libmonoboehm-2.0.so.1
  # Compress using UPX and compression level 9
  - upx -q -9 CSharpCompiler libmonoboehm-2.0.so.1
  # Run deployment script
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/CSharpCompiler ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  email: false
  slack:
    rooms:
      secure: "L7sn29xX0qRu0WI5N7i1xgiVgw+PsbAFlKf/snwwhrgIEQ+2vnbTpSFbCaP0EWho+x2rpFkiX0uULyAFj2jY1l1WYjF+TUNrtdiyEM4Lkt5o66cmKLQMoUCXwpFiKwnXlfiBcpNfkFjVhFedBr2MTv/ohKD0dCa4Bbalrgy/emo="

env:
  global:
    - PKG_CONFIG_PATH=/usr/lib/pkgconfig
    - secure: "NwFnFj8UFdw+rCwDbEek7FihZtpf3IeQ8yRy6gmmMZB+vXpRpvECW3jOKzMZw9mPp8qsvB88A9rIHDkveiFICwAJpzBo9FNwzaaceEPOrAdEkmCO8bTsaM/15PBeMAvR6JiFg2uOAnhZ92xSlslazaY/oU9K8M6Tvs3hzjgQ1KE="
