sudo: required
dist: trusty
language: csharp
mono: 4.4.0

addons:
  apt:
    packages:
    - upx-ucl
    - gcc-multilib

script:
  # Create temp files from source file and dependencies
  - mkbundle --static $SOURCE_FILES -c -o temp.c -oo temp.o
  # Create final file from temp files
  - gcc -g -o Compiler.x86_x64 -Wall temp.c `pkg-config --cflags --libs mono-2` temp.o
  # Download and setup x86 dependencies
  - sudo dpkg --add-architecture i386 && sudo apt-get update -qq || true
  - sudo apt-get download libmonoboehm-2.0-1:i386
  - dpkg -x libmonoboehm*.deb temp/
  # Create temp files from source file and dependencies
  - cp -P temp/usr/lib/libmonoboehm-2.0.so.1 temp/usr/lib/libmono-2.0.so
  - export AS="as --32"
  - mkbundle --static $SOURCE_FILES -c -o temp.c -oo temp.o
  - gcc -m32 -g -o Compiler.x86 -Wall temp.c -Ltemp/usr/lib/ `pkg-config --cflags --libs mono-2` temp.o

after_success:
  # Copy libmono shared library to project directory
  - mkdir x64 && cp /usr/lib/libmonoboehm-2.0.so.1.0.0 x64/libmonoboehm-2.0.so.1
  - mkdir x86 && cp temp/usr/lib/libmonoboehm-2.0.so.1.0.0 x86/libmonoboehm-2.0.so.1
  # Make executable and compress using UPX and compression level 9
  - chmod +x Compiler.x86_x64 Compiler.x86 x64/libmonoboehm-2.0.so.1 x86/libmonoboehm-2.0.so.1
  - upx -q -9 Compiler.x86_x64 Compiler.x86 x64/libmonoboehm-2.0.so.1 x86/libmonoboehm-2.0.so.1

notifications:
  email: false

env:
  global:
    - PKG_CONFIG_PATH=/usr/lib/pkgconfig
    - MONO_LIB=/usr/lib/mono/4.5
    - SOURCE_FILES="Resources/basic.exe $MONO_LIB/mscorlib.dll $MONO_LIB/System.dll $MONO_LIB/System.Core.dll $MONO_LIB/System.Xml.dll"
