sudo: required
dist: trusty
language: csharp
mono: 4.4.0

addons:
  apt:
    packages:
    - upx-ucl
    - gcc-multilib

script:
  # Create temp files from source file and dependencies
  - mkbundle --static $SOURCE_FILES -c -o temp.c -oo temp.o
  # Create final file from temp files
  - gcc -g -o CSharpCompiler -Wall temp.c `pkg-config --cflags --libs mono-2` temp.o
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq || true
  - sudo apt-get download libmonoboehm-2.0-1:i386
  - dpkg -x libmonoboehm*.deb temp/
  - cp -P temp/usr/lib/libmonoboehm-2.0.so.1 temp/usr/lib/libmono-2.0.so
  - export AS="as --32"
  - mkbundle --static $SOURCE_FILES -c -o temp.c -oo temp.o
  - gcc -m32 -g -o CSharpCompiler.x86 -Wall temp.c -Ltemp/usr/lib/ `pkg-config --cflags --libs mono-2` temp.o

after_success:
  # Copy libmono shared library to project directory
  - mkdir x86 && mkdir x64
  - cp /usr/lib/libmonoboehm-2.0.so.1.0.0 x64/libmonoboehm-2.0.so.1 && chmod +x x64/libmonoboehm-2.0.so.1
  - cp temp/usr/lib/libmonoboehm-2.0.so.1.0.0 x86/libmonoboehm-2.0.so.1 && chmod +x x86/libmonoboehm-2.0.so.1
  # Compress using UPX and compression level 9
  - upx -q -9 CSharpCompiler CSharpCompiler.x86 x64/libmonoboehm-2.0.so.1 x86/libmonoboehm-2.0.so.1
  # Make CSharpCompiler executable
  - chmod +x CSharpCompiler CSharpCompiler.x86
  # Run deployment script
  - "[[ $TRAVIS_REPO_SLUG == OxideMod/CSharpCompiler ]] && [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

deploy:
  provider: bintray
  file: descriptor.json
  user: oxidemod
  key:
    secure: "pwErqst+O17xmM0lGG8wbZQidIi4pN+hTyjsjqMgKSeQwIui7yNHXLnp7V+j2WicJc9qtyJD3/c5JbM+F39hU76REpsfQLrWAtML6lqc4PD/X0RKN5/vH+SfPNJOhTQML6QsC3oZYE2ypHwvqA1LVnRvCYGLEmg1ROZYE4vehuI="

env:
  global:
    - PKG_CONFIG_PATH=/usr/lib/pkgconfig
    - MONO_LIB=/usr/lib/mono/4.5
    - SOURCE_FILES="Resources/basic.exe $MONO_LIB/mscorlib.dll $MONO_LIB/System.dll $MONO_LIB/System.Core.dll $MONO_LIB/System.Xml.dll"
    - secure: "YC80Sew1MfQkDfEiZoTDrmgt4yK5PDAnm5UkvJ0b2MuYjLlaV1Pw/84NhUshPIX+jVSyZKFu9xevL1OU41IFWOihzNDFr3n4lFHHaWLgEPeXxdSiS/XMkv34CUx1D0JNUEAMmHZKa5FmLXPK2N9ypkrVUo7OnswbajoSa469yc8="
