name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: OxideCompiler\Oxide.Compiler.sln
      Project_Dir: OxideCompiler\src
      Project_Name: OxideCompiler\src\Oxide.Compiler.csproj
      PubProfiles: OxideCompiler\src\Properties\PublishProfiles
      PubOut: OxideCompiler\src\Artifacts

    steps:
    - name: Checkout Main
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: OxideCompiler
        
    - name: Checkout SingleFileExtractor
      uses: actions/checkout@v3
      with:
        repository: Droppers/SingleFileExtractor
        path: SingleFileExtractor
        fetch-depth: 0
        
    - name: Checkout PolySharp
      uses: actions/checkout@v3
      with:
        repository: Sergio0694/PolySharp
        path: PolySharp
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Decrypt SNK Key
      run: |
        $snk_cert_byte = [System.Convert]::FromBase64String("${{ secrets.STRONG_NAME }}")
        $certificatePath = Join-Path -Path OxideCompiler -ChildPath "sn.snk"
        [IO.File]::WriteAllBytes("$certificatePath", $snk_cert_byte)
      
    - name: Build the compiler
      run: dotnet build $env:Solution_Name
      
    - name: Publish
      run: |
        Get-ChildItem -Filter '*.pubxml' -Recurse | ForEach-Object {
          $name = $_.Name.Replace('.pubxml', '')
          dotnet publish "$env:Project_Name" "/p:PublishProfile=$name" -v q
        }
        
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.configuration }}.zip
        path: ${{ env.PubOut }}
      
    - name: Delete SNK Key
      run: Remove-Item (Join-Path -Path 'OxideCompiler' -ChildPath 'sn.snk')
